"""initial_schema

Revision ID: 2725d4eb8a75
Revises:
Create Date: 2026-05-21 10:35:20.511105

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "2725d4eb8a75"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "teams",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("plan", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
        sa.Column("settings", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "companies",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("team_id", sa.Uuid(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
        sa.Column("domain", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
        sa.Column("industry", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column("sub_industry", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("employee_count", sa.Integer(), nullable=True),
        sa.Column("employee_count_range", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
        sa.Column("revenue_estimate", sa.Numeric(), nullable=True),
        sa.Column("revenue_range", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
        sa.Column("funding_status", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
        sa.Column("funding_total", sa.Numeric(), nullable=True),
        sa.Column("location", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
        sa.Column("country", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
        sa.Column("timezone", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
        sa.Column("linkedin_url", sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True),
        sa.Column("twitter_url", sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True),
        sa.Column("facebook_url", sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True),
        sa.Column("logo_url", sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True),
        sa.Column("phone", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["teams.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("domain"),
    )
    op.create_index("idx_companies_domain", "companies", ["domain"], unique=False)
    op.create_index("idx_companies_industry", "companies", ["industry"], unique=False)
    op.create_index("idx_companies_team", "companies", ["team_id"], unique=False)
    op.create_index(op.f("ix_companies_team_id"), "companies", ["team_id"], unique=False)
    op.create_table(
        "integrations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("team_id", sa.Uuid(), nullable=False),
        sa.Column("service", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.Column("config", sa.JSON(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["teams.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "suppression_list",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("team_id", sa.Uuid(), nullable=False),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(length=320), nullable=False),
        sa.Column("reason", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.Column("source", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["teams.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_suppression_email", "suppression_list", ["email"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("team_id", sa.Uuid(), nullable=False),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(length=320), nullable=False),
        sa.Column("password_hash", sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=False),
        sa.Column("full_name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("role", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("last_login", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["teams.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_index(op.f("ix_users_team_id"), "users", ["team_id"], unique=False)
    op.create_table(
        "api_keys",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("team_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("key_hash", sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("permissions", sa.JSON(), nullable=True),
        sa.Column("last_used_at", sa.DateTime(), nullable=True),
        sa.Column("expires_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["teams.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("key_hash"),
    )
    op.create_table(
        "campaigns",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("team_id", sa.Uuid(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
        sa.Column("goal", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
        sa.Column("tone", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.Column("approval_mode", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
        sa.Column("send_limits", sa.JSON(), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["teams.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_campaigns_team_id"), "campaigns", ["team_id"], unique=False)
    op.create_table(
        "contacts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=True),
        sa.Column("first_name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column("last_name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column("full_name", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column("seniority", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
        sa.Column("department", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(length=320), nullable=True),
        sa.Column("email_status", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
        sa.Column("phone", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
        sa.Column("phone_status", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
        sa.Column("linkedin_url", sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True),
        sa.Column("location", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_contacts_company", "contacts", ["company_id"], unique=False)
    op.create_index("idx_contacts_email", "contacts", ["email"], unique=False)
    op.create_index("idx_contacts_linkedin", "contacts", ["linkedin_url"], unique=False)
    op.create_table(
        "email_accounts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("team_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("provider", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.Column("email_address", sqlmodel.sql.sqltypes.AutoString(length=320), nullable=False),
        sa.Column("access_token_encrypted", sqlmodel.sql.sqltypes.AutoString(length=4096), nullable=False),
        sa.Column("refresh_token_encrypted", sqlmodel.sql.sqltypes.AutoString(length=4096), nullable=True),
        sa.Column("provider_metadata", sa.JSON(), nullable=True),
        sa.Column("is_sending_account", sa.Boolean(), nullable=False),
        sa.Column("is_inbox_account", sa.Boolean(), nullable=False),
        sa.Column("daily_send_limit", sa.Integer(), nullable=False),
        sa.Column("sends_today", sa.Integer(), nullable=False),
        sa.Column("last_reset_at", sa.DateTime(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["teams.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "notifications",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("type", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("message", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("data", sa.JSON(), nullable=True),
        sa.Column("is_read", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_notifications_user", "notifications", ["user_id", "is_read", "created_at"], unique=False)
    op.create_table(
        "website_audits",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("website_score", sa.Integer(), nullable=True),
        sa.Column("page_speed_score", sa.Integer(), nullable=True),
        sa.Column("mobile_score", sa.Integer(), nullable=True),
        sa.Column("has_chatbot", sa.Boolean(), nullable=True),
        sa.Column("has_booking", sa.Boolean(), nullable=True),
        sa.Column("has_contact_form", sa.Boolean(), nullable=True),
        sa.Column("has_email_capture", sa.Boolean(), nullable=True),
        sa.Column("has_crm_form", sa.Boolean(), nullable=True),
        sa.Column("has_tracking_scripts", sa.Boolean(), nullable=True),
        sa.Column("has_support_widget", sa.Boolean(), nullable=True),
        sa.Column("broken_forms", sa.Boolean(), nullable=True),
        sa.Column("weak_cta", sa.Boolean(), nullable=True),
        sa.Column("technical_findings", sa.JSON(), nullable=True),
        sa.Column("conversion_findings", sa.JSON(), nullable=True),
        sa.Column("automation_findings", sa.JSON(), nullable=True),
        sa.Column("sales_angle", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("raw_content_url", sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_audits_company", "website_audits", ["company_id"], unique=False)
    op.create_table(
        "campaign_steps",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("campaign_id", sa.Uuid(), nullable=False),
        sa.Column("step_order", sa.Integer(), nullable=False),
        sa.Column("channel", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
        sa.Column("delay_days", sa.Integer(), nullable=False),
        sa.Column("template_type", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.Column("subject_template", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("body_template", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["campaigns.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "leads",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("team_id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=True),
        sa.Column("contact_id", sa.Uuid(), nullable=True),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.Column("pipeline_stage", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.Column("lead_score", sa.Integer(), nullable=False),
        sa.Column("score_band", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
        sa.Column("assigned_user_id", sa.Uuid(), nullable=True),
        sa.Column("last_contacted_at", sa.DateTime(), nullable=True),
        sa.Column("next_action", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column("next_action_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["assigned_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
        ),
        sa.ForeignKeyConstraint(
            ["contact_id"],
            ["contacts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["teams.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_leads_assigned", "leads", ["assigned_user_id"], unique=False)
    op.create_index("idx_leads_company", "leads", ["company_id"], unique=False)
    op.create_index("idx_leads_contact", "leads", ["contact_id"], unique=False)
    op.create_index("idx_leads_pipeline", "leads", ["pipeline_stage"], unique=False)
    op.create_index("idx_leads_score", "leads", ["lead_score"], unique=False)
    op.create_index("idx_leads_status", "leads", ["status"], unique=False)
    op.create_index("idx_leads_team", "leads", ["team_id"], unique=False)
    op.create_index(op.f("ix_leads_team_id"), "leads", ["team_id"], unique=False)
    op.create_table(
        "activity_logs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("team_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("lead_id", sa.Uuid(), nullable=True),
        sa.Column("action", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column("details", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["lead_id"],
            ["leads.id"],
        ),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["teams.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_activity_created", "activity_logs", ["created_at"], unique=False)
    op.create_index("idx_activity_lead", "activity_logs", ["lead_id"], unique=False)
    op.create_index("idx_activity_team", "activity_logs", ["team_id"], unique=False)
    op.create_table(
        "ai_research_reports",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("lead_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("company_summary", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("target_customer", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("likely_operational_pain", sa.JSON(), nullable=True),
        sa.Column("revenue_leakage_hypothesis", sa.JSON(), nullable=True),
        sa.Column("competitor_observations", sa.JSON(), nullable=True),
        sa.Column("recommended_outreach_angle", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("confidence", sa.Numeric(), nullable=True),
        sa.Column("model_used", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
        sa.Column("sources_used", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["lead_id"],
            ["leads.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_research_lead", "ai_research_reports", ["lead_id"], unique=False)
    op.create_table(
        "buying_signals",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("lead_id", sa.Uuid(), nullable=False),
        sa.Column("category", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column("evidence", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("source", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.Column("source_url", sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=True),
        sa.Column("confidence", sa.Numeric(), nullable=True),
        sa.Column("detection_method", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
        sa.Column("detected_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["lead_id"],
            ["leads.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_signals_category", "buying_signals", ["category"], unique=False)
    op.create_index("idx_signals_confidence", "buying_signals", ["confidence"], unique=False)
    op.create_index("idx_signals_lead", "buying_signals", ["lead_id"], unique=False)
    op.create_table(
        "campaign_enrollments",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("campaign_id", sa.Uuid(), nullable=False),
        sa.Column("lead_id", sa.Uuid(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
        sa.Column("current_step", sa.Integer(), nullable=False),
        sa.Column("next_step_at", sa.DateTime(), nullable=True),
        sa.Column("enrolled_at", sa.DateTime(), nullable=False),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["campaigns.id"],
        ),
        sa.ForeignKeyConstraint(
            ["lead_id"],
            ["leads.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_enrollments_campaign", "campaign_enrollments", ["campaign_id"], unique=False)
    op.create_index("idx_enrollments_lead", "campaign_enrollments", ["lead_id"], unique=False)
    op.create_table(
        "deduplication_matches",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("new_lead_id", sa.Uuid(), nullable=False),
        sa.Column("existing_lead_id", sa.Uuid(), nullable=False),
        sa.Column("match_type", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.Column("confidence", sa.Numeric(), nullable=False),
        sa.Column("resolved", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["existing_lead_id"],
            ["leads.id"],
        ),
        sa.ForeignKeyConstraint(
            ["new_lead_id"],
            ["leads.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "enrichment_records",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("lead_id", sa.Uuid(), nullable=False),
        sa.Column("provider", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.Column("enrichment_type", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.Column("data", sa.JSON(), nullable=True),
        sa.Column("confidence", sa.Numeric(), nullable=True),
        sa.Column("enriched_at", sa.DateTime(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["lead_id"],
            ["leads.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_enrichment_lead", "enrichment_records", ["lead_id"], unique=False)
    op.create_index("idx_enrichment_provider", "enrichment_records", ["provider"], unique=False)
    op.create_table(
        "jobs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("job_type", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
        sa.Column("lead_id", sa.Uuid(), nullable=True),
        sa.Column("campaign_id", sa.Uuid(), nullable=True),
        sa.Column("company_id", sa.Uuid(), nullable=True),
        sa.Column("error", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("max_retries", sa.Integer(), nullable=False),
        sa.Column("next_retry_at", sa.DateTime(), nullable=True),
        sa.Column("result", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["campaigns.id"],
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
        ),
        sa.ForeignKeyConstraint(
            ["lead_id"],
            ["leads.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_jobs_status", "jobs", ["status"], unique=False)
    op.create_index("idx_jobs_type", "jobs", ["job_type"], unique=False)
    op.create_table(
        "lead_scores",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("lead_id", sa.Uuid(), nullable=False),
        sa.Column("total_score", sa.Integer(), nullable=False),
        sa.Column("score_band", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
        sa.Column("buying_intent_score", sa.Integer(), nullable=True),
        sa.Column("urgency_score", sa.Integer(), nullable=True),
        sa.Column("operational_pain_score", sa.Integer(), nullable=True),
        sa.Column("scaling_pressure_score", sa.Integer(), nullable=True),
        sa.Column("budget_probability_score", sa.Integer(), nullable=True),
        sa.Column("website_weakness_score", sa.Integer(), nullable=True),
        sa.Column("contactability_score", sa.Integer(), nullable=True),
        sa.Column("recency_score", sa.Integer(), nullable=True),
        sa.Column("explanation", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("model_used", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["lead_id"],
            ["leads.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_scores_lead", "lead_scores", ["lead_id"], unique=False)
    op.create_table(
        "lead_sources",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("lead_id", sa.Uuid(), nullable=False),
        sa.Column("source_type", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.Column("source_url", sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=True),
        sa.Column("source_name", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
        sa.Column("raw_text", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("detected_signal_text", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("confidence", sa.Numeric(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["lead_id"],
            ["leads.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_sources_lead", "lead_sources", ["lead_id"], unique=False)
    op.create_index("idx_sources_type", "lead_sources", ["source_type"], unique=False)
    op.create_table(
        "outreach_messages",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("lead_id", sa.Uuid(), nullable=False),
        sa.Column("campaign_id", sa.Uuid(), nullable=True),
        sa.Column("campaign_step_id", sa.Uuid(), nullable=True),
        sa.Column("channel", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
        sa.Column("subject", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("body", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("personalization_sources", sa.JSON(), nullable=True),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
        sa.Column("approved_by", sa.Uuid(), nullable=True),
        sa.Column("approved_at", sa.DateTime(), nullable=True),
        sa.Column("sent_at", sa.DateTime(), nullable=True),
        sa.Column("delivered_at", sa.DateTime(), nullable=True),
        sa.Column("opened_at", sa.DateTime(), nullable=True),
        sa.Column("clicked_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["approved_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["campaigns.id"],
        ),
        sa.ForeignKeyConstraint(
            ["campaign_step_id"],
            ["campaign_steps.id"],
        ),
        sa.ForeignKeyConstraint(
            ["lead_id"],
            ["leads.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_messages_campaign", "outreach_messages", ["campaign_id"], unique=False)
    op.create_index("idx_messages_lead", "outreach_messages", ["lead_id"], unique=False)
    op.create_index("idx_messages_status", "outreach_messages", ["status"], unique=False)
    op.create_table(
        "pipeline_transitions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("lead_id", sa.Uuid(), nullable=False),
        sa.Column("from_stage", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
        sa.Column("to_stage", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.Column("reason", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("transitioned_by", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["lead_id"],
            ["leads.id"],
        ),
        sa.ForeignKeyConstraint(
            ["transitioned_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_pipeline_lead", "pipeline_transitions", ["lead_id"], unique=False)
    op.create_table(
        "follow_up_tasks",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("lead_id", sa.Uuid(), nullable=False),
        sa.Column("campaign_enrollment_id", sa.Uuid(), nullable=True),
        sa.Column("task_type", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.Column("due_at", sa.DateTime(), nullable=True),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
        sa.Column("data", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["campaign_enrollment_id"],
            ["campaign_enrollments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["lead_id"],
            ["leads.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_followup_due", "follow_up_tasks", ["due_at"], unique=False)
    op.create_index("idx_followup_lead", "follow_up_tasks", ["lead_id"], unique=False)
    op.create_table(
        "replies",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("lead_id", sa.Uuid(), nullable=False),
        sa.Column("message_id", sa.Uuid(), nullable=True),
        sa.Column("channel", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
        sa.Column("subject", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("body", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("from_email", sqlmodel.sql.sqltypes.AutoString(length=320), nullable=True),
        sa.Column("from_name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column("received_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["lead_id"],
            ["leads.id"],
        ),
        sa.ForeignKeyConstraint(
            ["message_id"],
            ["outreach_messages.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "reply_classifications",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("reply_id", sa.Uuid(), nullable=False),
        sa.Column("lead_id", sa.Uuid(), nullable=False),
        sa.Column("classification", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.Column("subtype", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
        sa.Column("confidence", sa.Numeric(), nullable=False),
        sa.Column("summary", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("recommended_action", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column("draft_response", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("model_used", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
        sa.Column("reviewed_by", sa.Uuid(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["lead_id"],
            ["leads.id"],
        ),
        sa.ForeignKeyConstraint(
            ["reply_id"],
            ["replies.id"],
        ),
        sa.ForeignKeyConstraint(
            ["reviewed_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_reply_class_lead", "reply_classifications", ["lead_id"], unique=False)
    op.create_index("idx_reply_class_reply", "reply_classifications", ["reply_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_reply_class_reply", table_name="reply_classifications")
    op.drop_index("idx_reply_class_lead", table_name="reply_classifications")
    op.drop_table("reply_classifications")
    op.drop_table("replies")
    op.drop_index("idx_followup_lead", table_name="follow_up_tasks")
    op.drop_index("idx_followup_due", table_name="follow_up_tasks")
    op.drop_table("follow_up_tasks")
    op.drop_index("idx_pipeline_lead", table_name="pipeline_transitions")
    op.drop_table("pipeline_transitions")
    op.drop_index("idx_messages_status", table_name="outreach_messages")
    op.drop_index("idx_messages_lead", table_name="outreach_messages")
    op.drop_index("idx_messages_campaign", table_name="outreach_messages")
    op.drop_table("outreach_messages")
    op.drop_index("idx_sources_type", table_name="lead_sources")
    op.drop_index("idx_sources_lead", table_name="lead_sources")
    op.drop_table("lead_sources")
    op.drop_index("idx_scores_lead", table_name="lead_scores")
    op.drop_table("lead_scores")
    op.drop_index("idx_jobs_type", table_name="jobs")
    op.drop_index("idx_jobs_status", table_name="jobs")
    op.drop_table("jobs")
    op.drop_index("idx_enrichment_provider", table_name="enrichment_records")
    op.drop_index("idx_enrichment_lead", table_name="enrichment_records")
    op.drop_table("enrichment_records")
    op.drop_table("deduplication_matches")
    op.drop_index("idx_enrollments_lead", table_name="campaign_enrollments")
    op.drop_index("idx_enrollments_campaign", table_name="campaign_enrollments")
    op.drop_table("campaign_enrollments")
    op.drop_index("idx_signals_lead", table_name="buying_signals")
    op.drop_index("idx_signals_confidence", table_name="buying_signals")
    op.drop_index("idx_signals_category", table_name="buying_signals")
    op.drop_table("buying_signals")
    op.drop_index("idx_research_lead", table_name="ai_research_reports")
    op.drop_table("ai_research_reports")
    op.drop_index("idx_activity_team", table_name="activity_logs")
    op.drop_index("idx_activity_lead", table_name="activity_logs")
    op.drop_index("idx_activity_created", table_name="activity_logs")
    op.drop_table("activity_logs")
    op.drop_index(op.f("ix_leads_team_id"), table_name="leads")
    op.drop_index("idx_leads_team", table_name="leads")
    op.drop_index("idx_leads_status", table_name="leads")
    op.drop_index("idx_leads_score", table_name="leads")
    op.drop_index("idx_leads_pipeline", table_name="leads")
    op.drop_index("idx_leads_contact", table_name="leads")
    op.drop_index("idx_leads_company", table_name="leads")
    op.drop_index("idx_leads_assigned", table_name="leads")
    op.drop_table("leads")
    op.drop_table("campaign_steps")
    op.drop_index("idx_audits_company", table_name="website_audits")
    op.drop_table("website_audits")
    op.drop_index("idx_notifications_user", table_name="notifications")
    op.drop_table("notifications")
    op.drop_table("email_accounts")
    op.drop_index("idx_contacts_linkedin", table_name="contacts")
    op.drop_index("idx_contacts_email", table_name="contacts")
    op.drop_index("idx_contacts_company", table_name="contacts")
    op.drop_table("contacts")
    op.drop_index(op.f("ix_campaigns_team_id"), table_name="campaigns")
    op.drop_table("campaigns")
    op.drop_table("api_keys")
    op.drop_index(op.f("ix_users_team_id"), table_name="users")
    op.drop_table("users")
    op.drop_index("idx_suppression_email", table_name="suppression_list")
    op.drop_table("suppression_list")
    op.drop_table("integrations")
    op.drop_index(op.f("ix_companies_team_id"), table_name="companies")
    op.drop_index("idx_companies_team", table_name="companies")
    op.drop_index("idx_companies_industry", table_name="companies")
    op.drop_index("idx_companies_domain", table_name="companies")
    op.drop_table("companies")
    op.drop_table("teams")
    # ### end Alembic commands ###
